# Whitelist of Players that aren't affected by the cooldown.
whitelist:
  name:
    - testuser
cooldown: # Configuration of Cooldown Display Message / Cooldown Period
  period: 5
  message: &lYou have a cooldown for %cooldown% &csecond(s)




